language: node_js
node_js:
  - "lts/*"

before_install:
  - yarn

before_script:
  - yarn lint
  - yarn test

services:
  - docker

script:
  - yarn build
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - make image-build image-publish IMAGE_VERSION=$TRAVIS_BRANCH

branches:
  only:
    - develop
    - tags
