// API
export const CONNECTION_STATE_CHANGE = 'CONNECTION_STATE_CHANGE'
export const SIGNALING_CLIENT = 'SIGNALING_CLIENT'
export const SIGNALING_CLIENT_SHUTDOWN = 'SIGNALING_CLIENT_SHUTDOWN'
export const RECEIVED_CONFIG = 'RECEIVED_CONFIG'
export const RECEIVED_CONFIG_ERROR = 'RECEIVED_CONFIG_ERROR'

// Calls
export const JOIN_CALL = 'JOIN_CALL'
export const LEAVE_CALL = 'LEAVE_CALL'

// Connections
export const PEER_CONNECTION_ADDED = 'PEER_CONNECTION_ADDED'
export const PEER_CONNECTION_UPDATED = 'PEER_CONNECTION_UPDATED'
export const PEER_CONNECTION_REMOVED = 'PEER_CONNECTION_REMOVED'

// Devices
export const DEVICES = 'DEVICES'
export const CAMERA_PERMISSION_DENIED = 'CAMERA_PERMISSION_DENIED'
export const MICROPHONE_PERMISSION_DENIED = 'MICROPHONE_PERMISSION_DENIED'
export const DEVICE_CAPTURE = 'DEVICE_CAPTURE'

// Media
export const ADD_MEDIA = 'ADD_MEDIA'
export const REMOVE_MEDIA = 'REMOVE_MEDIA'
export const MEDIA_UPDATED = 'MEDIA_UPDATED'

// Peers
export const PEER_ONLINE = 'PEER_ONLINE'
export const PEER_OFFLINE = 'PEER_OFFLINE'
export const PEER_UPDATED = 'PEER_UPDATED'

// Rooms
export const JOIN_ROOM = 'JOIN_ROOM'
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS'
export const JOIN_ROOM_FAILED = 'JOIN_ROOM_FAILED'
export const LEAVE_ROOM = 'LEAVE_ROOM'
export const DESTROY_ROOM = 'DESTROY_ROOM'

// User
export const SET_USER_PREFERENCE = 'SET_USER_PREFERENCE'
